### ISSUE TITLE
provide a callback based mutate API for easier load + mutate + save of resources

### ISSUE THREAD

**Issue by jstrachan** [jimmidyson/kubernetes-client#1]
e.g. to resize an RC:
```
replicationController("foo").namespace("bah").update(rc -> rc.getSpec().setReplicas(12))
```

**Comment by jimmidyson** [comment]
Here's an example: https://github.com/jimmidyson/kubernetes-client/blob/master/src/test/java/io/fabric8/kubernetes/UpdateExamples.java#L19-L28

Still some work to do to use generics a little better, only working for pods right now but nearly there.

**Comment by jimmidyson** [comment]
Even closer but can't figure out how to use the editable stuff from the kubernetes model - hoping @iocanel can help :) Problem is at https://github.com/jimmidyson/kubernetes-client/blob/master/src/main/java/io/fabric8/kubernetes/Resource.java#L109 - can't cast appropriately.

**Comment by jimmidyson** [comment]
Sorted :)
